### ISSUE TITLE
英文数据部分问题

### ISSUE THREAD

**Issue by memorymr** [buppt/ChineseNRE#9]
中文数据集成功跑通了，不过英文数据集并没有成功，报错如下：
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    y = model(sentence,pos1,pos2)  
  File "/home/jfy/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfy/下载/NER/BiLSTM_ATT.py", line 63, in forward
    embeds = torch.cat((self.word_embeds(sentence),self.pos1_embeds(pos1),self.pos2_embeds(pos2)),2)
  File "/home/jfy/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfy/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/jfy/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at /opt/conda/conda-bld/pytorch_1535488076166/work/aten/src/TH/generic/THTensorMath.cpp:352

**Comment by 1216884492** [comment]
我也遇到了这个问题,是通过调整train.py中的POS_SIZE来解决的,您可以尝试一下

**Comment by memorymr** [comment]
好的，谢谢

**Comment by 1216884492** [comment]
不好意思，打扰了。我想问一下您在使用开源项目的时候有没有遇到过拟合问题？我调整了多组dropout参数和l2正则，始终没有解决，想向您咨询一下


 
---原始邮件---
发件人: "memorymr"<notifications@github.com>
发送时间: 2019年5月13日(星期一) 晚上9:06
收件人: "buppt/ChineseNRE"<ChineseNRE@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"1216884492"<1827404979@qq.com>;
主题: Re: [buppt/ChineseNRE] 英文数据部分问题 (#9)



好的，谢谢

**Comment by memorymr** [comment]
我在使用的时候也发现了这个问题，目前还没有找到好的解决办法，你可以尝试修改一下学习率和Batch大小，可能会有一点效果。

**Comment by 1216884492** [comment]
好的,可否加一下您邮箱?想进一步沟通模型使用情况

**Comment by memorymr** [comment]
279791061@qq.com
